### ISSUE TITLE
Ability to show specific versions?

### ISSUE THREAD

**Issue by dhobbs** [mbi/django-front#11]
Hi,

django-front looks like an awesome fit for a project I'm working on! Thanks :)

The only thing I'm missing is the ability to 'pin' content to a specific version. We have an edit/approve workflow that allows a 'normal' user to edit content on their page but it has to be approved by a staff member before it goes live to the world. I'm thinking of storing the PK of the placeholderhistory in our page model and rendering that content, instead of using the default front template tag (with the slight complication that the owning user always sees the latest version).

I just wanted to check if there was another way or if it might be worth trying to add it on a fork and submitting it as a PR?

**Comment by mbi** [comment]
Hi Darren, I think your requirements (content blocks linked to page objects, publication workflow, …) would be easier fulfilled with a _real_ CMS (django-cms comes to mind), don't you agree?
