### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by rafalolszewskii** [mbi/django-front#12]
Does it work well with translations, for an example, I have a button with text in it: `{% trans "start free trial" %}` if I wrap the whole tag trans with `{% front_edit "my_button" %}` will it work on other languages respectively ?

Alright, I've managed to test it on my own, correcting the question (or making a request of it):

Could you make support for translations ?

**Comment by mbi** [comment]
Nope, it doesn't work like that, the content of the `front_edit` tag will be rendered and saved in the database. So ideally you want to pass the current language to `front_edit` and have the whole content handled by django-front, e.g.
```
{% front_edit "my_button" request.LANGUAGE_CODE %}
<a href="#">start free trial</a>
{% end_front_edit %}
```
So you can change the content of your button and have a different version per language.

Makes sense?

**Comment by rafalolszewskii** [comment]
Awesome, it makes sense now :smile: that's what I've been looking for
