### ISSUE TITLE
How to set custom limit when uploading file / image?

### ISSUE THREAD

**Issue by iColdPlayer** [mbi/django-front#19]
Hi, thank's for making this Django package, it's really easy to use. 
I've been developing my own CMS using this package. but somehow, when I upload an image with over `6MB`, I got the following error, and the image can't be saved:
```
Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.
Bad Request: /id/edit/save/
"POST /id/edit/save/ HTTP/1.1" 400 26
```

Is there any documentation to set the upload limit when using `summernote` editor & `django-front`?

**Comment by llazzaro** [comment]
Hi,
DATA_UPLOAD_MAX_MEMORY_SIZE is a django setting, you can check how to use it here:
https://docs.djangoproject.com/en/dev/ref/settings/#data-upload-max-memory-size

**Comment by mbi** [comment]
Pretty much what @llazzaro said, thanks!
