### ISSUE TITLE
How to improve Frontend Editing in Django?

### ISSUE THREAD

**Issue by davidjeba** [mbi/django-front#21]
from this 
https://www.django-cms.org/en/frontend-editing/

to this
https://kepler.app/

**Comment by mbi** [comment]
I'm sorry, what's your point?

**Comment by davidjeba** [comment]
My Point is,
https://www.django-cms.org/en/frontend-editing/ is really awesome
missing: drag and drop inline editing, very dependent on wysiwyg editors

and it could be more awesome if it can work like 
https://kepler.app/
advantages: more fluid inline editing, almost work like a no-code frontend editor
[eg: imagine a blogger running their website on django. they might not have technical expertise to work on editors, they are more inclined to wix.com like frontend system]

**Comment by mbi** [comment]
Fine, but why opening an issue on django-front and not on django-cms, then? :man_shrugging:

**Comment by davidjeba** [comment]
Ok, I assumed that if the core templating system supported such features then building a frontend layer would be possible
core features being enhanced would be better than building a radically new UX which is not compatible to the core would lead to a messy situations.

Just a pointer to the core team, to consider for future release

**Comment by mbi** [comment]
Ok I understand now... django-front is not at all related to django-cms, they are completely separated projects and are used in different scenarios. Closing now but thanks for the pointes.
